version: "3"
services:
  web:
    image: php:7.1.9-apache
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - "./db/data:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root"
